### ISSUE TITLE
Warning during install

### ISSUE THREAD

**Issue by jeanmonod** [liip/discourse-multilingual-support#7]
This warning is display during the rebuild

    /var/www/discourse/plugins/discourse-multilingual-support/lib/single_sign_on.rb:4: warning: already initialized constant SingleSignOn::ACCESSORS
    /var/www/discourse/lib/single_sign_on.rb:2: warning: previous definition of ACCESSORS was here

**Comment by EmbusQade** [comment]
f6853cb682782fefe97f34cf90c18cc84523c741
